source :rubygems


gem "unicorn"
gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  gem "newsly"
  gem "letter_opener"
  gem "spork"
  gem "sqlite3"
  gem "rspec-rails"
  gem "capybara"
  gem "capybara-webkit"
  gem "database_cleaner"
end